package:
  name: valence
  version: "0.0.1.2"

source:
  git_rev: d55cdc6b1aad0dbfae679a4ce0a58b8b2147772c
  git_url: https://github.com/blakeboswell/valence.git

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
  run:
    - python
    - pandas
    - scipy

test:
  imports:
    - valence
    - valence.build

about:
  home: https://github.com/blakeboswell/valence
  license: BSD-3
  license_file: LICENSE
