package:
  name: valence
  version: "0.0.2"

source:
  git_rev: dfd3034b66bffd7afe15a33da73634326c8243c4 
  git_url: https://github.com/blakeboswell/valence.git

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
  run:
    - python
    - pandas
    - scipy

test:
  imports:
    - valence
    - valence.build

about:
  home: https://github.com/blakeboswell/valence
  license: BSD-3
  license_file: LICENSE
