package:
  name: pyvalence
  version: "0.0.1.2"

source:
  git_rev: 515ab24c7bf5d8122ac217df7184f1e0b0da6df2
  git_url: https://github.com/audere-labs/pyvalence.git

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
  run:
    - python
    - pandas
    - scipy

test:
  imports:
    - pyvalence
    - pyvalence.build

about:
  home: https://github.com/audere-labs/pyvalence
  license: BSD-3
  license_file: LICENSE
